name: AWS Lambda python code unit test

on:
  push:
    branches:
      - feature/lambda-for-iotcore-rule-engine

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-lambda
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          cd lambdasrc
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

